name: PR Automation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  format-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set PR Title based on branch name
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prTitle = context.payload.pull_request.title;
            const branchName = context.payload.pull_request.head.ref;

            if (!prTitle.startsWith("Feat: ")) {
              const newTitle = `Feat: ${branchName.replace("feat/", "")}`;
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                title: newTitle
              });
              console.log(`Updated PR title to: ${newTitle}`);
            }

  generate-commit-summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Get PR Commits and Format Summary
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            const commits = await github.rest.pulls.listCommits({
              owner,
              repo,
              pull_number: prNumber
            });

            let commitMessages = commits.data.map(commit => `- ${commit.commit.message.split('\n')[0]}`).join('\n');

            // ✅ Hier setzen wir nun die Extended Description explizit
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            const newBody = `### Squash Merge Summary\n${commitMessages}`;

            await github.rest.pulls.update({
              owner,
              repo,
              pull_number: prNumber,
              title: pr.data.title,  // PR-Titel beibehalten
              body: newBody           // ✅ Extended Description setzen
            });

            console.log("Updated PR body for Squash Merge.");
